"""Frame types for the voice agent pipeline.

All data flowing through the pipeline is a Frame. Frames are simple
dataclasses — no behavior, no inheritance chains.
"""

from __future__ import annotations

import time
from dataclasses import dataclass, field
from enum import Enum, auto
from typing import Any

import numpy as np


class FrameDirection(Enum):
    DOWNSTREAM = auto()
    UPSTREAM = auto()


# ---------------------------------------------------------------------------
# Base
# ---------------------------------------------------------------------------


@dataclass
class Frame:
    """Base frame — all data in the pipeline is a Frame."""

    timestamp: float = field(default_factory=time.monotonic)
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass
class SystemFrame(Frame):
    """High-priority control frame. Processed before data frames."""

    pass


# ---------------------------------------------------------------------------
# Audio
# ---------------------------------------------------------------------------


@dataclass
class AudioFrame(Frame):
    """Raw audio data."""

    audio: bytes = b""
    sample_rate: int = 16000
    num_channels: int = 1
    sample_width: int = 2  # bytes per sample (2 = int16)

    @property
    def duration_ms(self) -> float:
        if not self.audio:
            return 0.0
        return len(self.audio) / (self.sample_width * self.num_channels * self.sample_rate) * 1000

    def to_numpy(self) -> np.ndarray:
        """Convert to float32 numpy array normalized to [-1, 1]."""
        return np.frombuffer(self.audio, dtype=np.int16).astype(np.float32) / 32768.0

    @classmethod
    def from_numpy(cls, data: np.ndarray, sample_rate: int = 16000) -> AudioFrame:
        """Create from float32 numpy array."""
        pcm = (data * 32768.0).clip(-32768, 32767).astype(np.int16)
        return cls(audio=pcm.tobytes(), sample_rate=sample_rate)


@dataclass
class InputAudioFrame(AudioFrame):
    """Audio from the user (microphone/telephone)."""

    pass


@dataclass
class OutputAudioFrame(AudioFrame):
    """Audio going to the user (speaker/telephone)."""

    pass


@dataclass
class UninterruptibleAudioFrame(OutputAudioFrame):
    """Output audio that survives interruption clearing (for backchannels)."""

    pass


@dataclass
class TTSAudioFrame(OutputAudioFrame):
    """Audio generated by TTS from LLM text."""

    source_text: str = ""


# ---------------------------------------------------------------------------
# Text / Transcription
# ---------------------------------------------------------------------------


@dataclass
class TranscriptionFrame(Frame):
    """Final transcription from STT."""

    text: str = ""
    language: str = ""
    confidence: float = 0.0


@dataclass
class InterimTranscriptionFrame(Frame):
    """Interim/partial transcription from STT."""

    text: str = ""
    language: str = ""


@dataclass
class LLMResponseFrame(Frame):
    """Text chunk from LLM streaming response."""

    text: str = ""
    is_final: bool = False


# ---------------------------------------------------------------------------
# Control
# ---------------------------------------------------------------------------


@dataclass
class StartFrame(SystemFrame):
    """Pipeline has started."""

    pass


@dataclass
class StopFrame(SystemFrame):
    """Pipeline should stop."""

    pass


@dataclass
class InterruptionFrame(SystemFrame):
    """User interrupted the agent — cancel current output."""

    pass


# ---------------------------------------------------------------------------
# VAD
# ---------------------------------------------------------------------------


class VADState(Enum):
    SPEAKING = auto()
    SILENCE = auto()


@dataclass
class VADEvent(SystemFrame):
    """Voice activity detection state change."""

    state: VADState = VADState.SILENCE
    confidence: float = 0.0


# ---------------------------------------------------------------------------
# Turn-taking / Backchannel
# ---------------------------------------------------------------------------


@dataclass
class UserTurnEndFrame(SystemFrame):
    """Turn-taking decided the user finished speaking."""

    text: str = ""
    confidence: float = 0.0
    prosodic_features: dict[str, float] = field(default_factory=dict)


@dataclass
class BotSpeakingFrame(SystemFrame):
    """Bot started or stopped speaking."""

    is_speaking: bool = True


@dataclass
class BackchannelTriggerFrame(SystemFrame):
    """Internal signal: a backchannel should be injected."""

    signal: str = "continuer"
    source: str = "heuristic"
